#! /bin/sh

sxhkd &
polybar -r PolybarTop &
polybar -r PolybarBot &
compton &
reload_xrdb &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width            2
bspc config border_radius           5
bspc config window_gap              12

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true

bspc config focus_follows_pointer   true
bspc config click_to_focus          button1
bspc config pointer_modifier        mod1
bspc config pointer_action1	        move
bspc config pointer_action2 	    resize_corner

bspc rule -a URxvt:float            state=floating
bspc rule -a discord                state=floating
bspc rule -a Chromium               state=floating rectangle=1600x900+158+88
